version: '3.8'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dreamjob
    ports:
      - "3306:3306"
    networks:
      - dreamjob-net

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    networks:
      - dreamjob-net

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - dreamjob-net

  kafka:
    image: bitnami/kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - dreamjob-net
    depends_on:
      - zookeeper
  eureka-server:
    build: ./backend/eureka-server
    ports:
      - "8761:8761"
    networks:
      - dreamjob-net

  api-gateway:
    build: ./backend/api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - config-server
    networks:
      - dreamjob-net

  auth-service:
    build: ./backend/auth-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - config-server
    networks:
      - dreamjob-net

  config-server:
    build: ./backend/config-server
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server
    networks:
      - dreamjob-net

  employer-service:
    build: ./backend/employer-service
    depends_on:
      - mysql
      - kafka
      - eureka-server
      - config-server
    networks:
      - dreamjob-net

  jobopening-service:
    build: ./backend/jobopening-service
    depends_on:
      - mongodb
      - kafka
      - eureka-server
    networks:
      - dreamjob-net

  jobseeker-service:
    build: ./backend/jobseeker-service
    depends_on:
      - mysql
      - eureka-server
    networks:
      - dreamjob-net

  application-service:
    build: ./backend/application-service
    depends_on:
      - mongodb
      - eureka-server
    networks:
      - dreamjob-net

  angular-shell:
    build: ./frontend/shell
    ports:
      - "4200:80"
    depends_on:
      - api-gateway
    networks:
      - dreamjob-net


networks:
  dreamjob-net:
    driver: bridge