version: '3.8'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dreamjob
    ports:
      - "3306:3306"
    networks:
      - dreamjob-net

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    networks:
      - dreamjob-net

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - dreamjob-net

  kafka:
    image: bitnami/kafka:3.6.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes                     # enable KRaft mode
      - KAFKA_CFG_PROCESS_ROLES=broker,controller  # this node is both broker + controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_NODE_ID=1                        # unique ID for this node
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CLUSTER_ID=kraft-cluster-1           # cluster ID, must be same across nodes
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - dreamjob-net

  eureka-server:
    build: ./backend/eureka-server
    ports:
      - "8761:8761"
    networks:
      - dreamjob-net

  api-gateway:
    build: ./backend/api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - config-server
    networks:
      - dreamjob-net

  auth-service:
    build: ./backend/auth-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - config-server
    networks:
      - dreamjob-net

  config-server:
    build: ./backend/config-server
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server
    networks:
      - dreamjob-net

  employer-service:
    build: ./backend/employer-service
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - mysql
      - kafka
      - eureka-server
      - config-server
    networks:
      - dreamjob-net

  jobopening-service:
    build: ./backend/jobopening-service
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - mongodb
      - kafka
      - eureka-server
    networks:
      - dreamjob-net

  jobseeker-service:
    build: ./backend/jobseeker-service
    depends_on:
      - mysql
      - eureka-server
    networks:
      - dreamjob-net

  jobapplication-service:
    build: ./backend/jobapplication-service
    depends_on:
      - mongodb
      - eureka-server
    networks:
      - dreamjob-net

  angular-shell:
    build: ./frontend/shell
    ports:
      - "4200:80"
    depends_on:
      - api-gateway
    networks:
      - dreamjob-net


networks:
  dreamjob-net:
    driver: bridge