version: '3.8'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dreamjob
    ports:
      - "3306:3306"

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  eureka-server:
    build: ./backend/eureka-server
    ports:
      - "8761:8761"

  api-gateway:
    build: ./backend/api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server

  auth-service:
    build: ./backend/auth-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server

  config-server:
    build: ./backend/config-server
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server

  employer-service:
    build: ./backend/employer-service
    depends_on:
      - mysql
      - kafka
      - eureka-server

  jobopening-service:
    build: ./backend/jobopening-service
    depends_on:
      - mongodb
      - kafka
      - eureka-server

  jobseeker-service:
    build: ./backend/jobseeker-service
    depends_on:
      - mysql
      - eureka-server

  application-service:
    build: ./backend/application-service
    depends_on:
      - mongodb
      - eureka-server

  angular-shell:
    build: ./frontend/shell
    ports:
      - "4200:80"
    depends_on:
      - api-gateway
